package mypack;

// Generated Jul 23, 2014 8:39:56 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MembershipReg generated by hbm2java
 */
@Entity
@Table(name = "membership_reg", catalog = "fleet")
public class MembershipReg implements java.io.Serializable {

	private Integer memNo;
	private String passwd;
	private String FName;
	private String LName;
	private String addr;
	private String emailId;
	private String city;
	private Integer hmPhone;
	private String ccType;
	private String licence;
	private Date licValidthru;
	private Integer passPortNo;
	private Date passportValidthru;
	private Date dob;
	private Date DOfReg;
	private Integer zip;
	
	
	@Column(name = "zip")
	public Integer getZip() {
		return zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}

	private Integer cell;
	private Integer idp;

	public MembershipReg() {
	}

	public MembershipReg(Date licValidthru, Date passportValidthru, Date dob,
			Date DOfReg) {
		this.licValidthru = licValidthru;
		this.passportValidthru = passportValidthru;
		this.dob = dob;
		this.DOfReg = DOfReg;
	}

	public MembershipReg(String passwd, String FName, String LName,
			String addr, String emailId, String city, Integer hmPhone,
			String ccType, String licence, Date licValidthru,
			Integer passPortNo, Date passportValidthru, Date dob, Date DOfReg,
			Integer zip, Integer cell, Integer idp) {
		this.passwd = passwd;
		this.FName = FName;
		this.LName = LName;
		this.addr = addr;
		this.emailId = emailId;
		this.city = city;
		this.hmPhone = hmPhone;
		this.ccType = ccType;
		this.licence = licence;
		this.licValidthru = licValidthru;
		this.passPortNo = passPortNo;
		this.passportValidthru = passportValidthru;
		this.dob = dob;
		this.DOfReg = DOfReg;
		this.zip = zip;
		this.cell = cell;
		this.idp = idp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Mem_no", unique = true, nullable = false)
	public Integer getMemNo() {
		return this.memNo;
	}

	public void setMemNo(Integer memNo) {
		this.memNo = memNo;
	}

	@Column(name = "passwd", length = 15)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "F_name", length = 15)
	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	@Column(name = "L_name", length = 15)
	public String getLName() {
		return this.LName;
	}

	public void setLName(String LName) {
		this.LName = LName;
	}

	@Column(name = "Addr", length = 50)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "email_id", length = 20)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "City", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Hm_phone")
	public Integer getHmPhone() {
		return this.hmPhone;
	}

	public void setHmPhone(Integer hmPhone) {
		this.hmPhone = hmPhone;
	}

	@Column(name = "CC_type", length = 20)
	public String getCcType() {
		return this.ccType;
	}

	public void setCcType(String ccType) {
		this.ccType = ccType;
	}

	@Column(name = "Licence", length = 20)
	public String getLicence() {
		return this.licence;
	}

	public void setLicence(String licence) {
		this.licence = licence;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Lic_validthru", nullable = true, length = 19)
	public Date getLicValidthru() {
		return this.licValidthru;
	}

	public void setLicValidthru(Date licValidthru) {
		this.licValidthru = licValidthru;
	}

	@Column(name = "PassPort_no")
	public Integer getPassPortNo() {
		return this.passPortNo;
	}

	public void setPassPortNo(Integer passPortNo) {
		this.passPortNo = passPortNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Passport_validthru", nullable = true, length = 19)
	public Date getPassportValidthru() {
		return this.passportValidthru;
	}

	public void setPassportValidthru(Date passportValidthru) {
		this.passportValidthru = passportValidthru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", nullable = true, length = 19)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_of_reg", nullable = true, length = 19)
	public Date getDOfReg() {
		return this.DOfReg;
	}

	public void setDOfReg(Date DOfReg) {
		this.DOfReg = DOfReg;
	}

	
	/*public Integer getZip() {
		return this.zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}
*/
	@Column(name = "cell")
	public Integer getCell() {
		return this.cell;
	}

	public void setCell(Integer cell) {
		this.cell = cell;
	}

	@Column(name = "IDP")
	public Integer getIdp() {
		return this.idp;
	}

	public void setIdp(Integer idp) {
		this.idp = idp;
	}

	@Override
	public String toString() {
		return "MembershipReg [memNo=" + memNo + ", passwd=" + passwd
				+ ", FName=" + FName + ", LName=" + LName + ", addr=" + addr
				+ ", emailId=" + emailId + ", city=" + city + ", hmPhone="
				+ hmPhone + ", ccType=" + ccType + ", licence=" + licence
				+ ", licValidthru=" + licValidthru + ", passPortNo="
				+ passPortNo + ", passportValidthru=" + passportValidthru
				+ ", dob=" + dob + ", DOfReg=" + DOfReg + ", zip=" + zip
				+ ", cell=" + cell + ", idp=" + idp + "]";
	}

}
